// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package jupiter

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6a975c40DecodeGithubComHumangrassPriceKeeperInternalUsecasesJupiter(in *jlexer.Lexer, out *PriceResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "data":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Data = make(map[string]PriceData)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 PriceData
					easyjson6a975c40DecodeGithubComHumangrassPriceKeeperInternalUsecasesJupiter1(in, &v1)
					(out.Data)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		case "timeTaken":
			out.TimeTaken = float64(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40EncodeGithubComHumangrassPriceKeeperInternalUsecasesJupiter(out *jwriter.Writer, in PriceResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix[1:])
		if in.Data == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v2First := true
			for v2Name, v2Value := range in.Data {
				if v2First {
					v2First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v2Name))
				out.RawByte(':')
				easyjson6a975c40EncodeGithubComHumangrassPriceKeeperInternalUsecasesJupiter1(out, v2Value)
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"timeTaken\":"
		out.RawString(prefix)
		out.Float64(float64(in.TimeTaken))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PriceResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6a975c40EncodeGithubComHumangrassPriceKeeperInternalUsecasesJupiter(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PriceResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6a975c40EncodeGithubComHumangrassPriceKeeperInternalUsecasesJupiter(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PriceResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6a975c40DecodeGithubComHumangrassPriceKeeperInternalUsecasesJupiter(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PriceResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6a975c40DecodeGithubComHumangrassPriceKeeperInternalUsecasesJupiter(l, v)
}
func easyjson6a975c40DecodeGithubComHumangrassPriceKeeperInternalUsecasesJupiter1(in *jlexer.Lexer, out *PriceData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "type":
			out.Type = string(in.String())
		case "price":
			out.Price = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40EncodeGithubComHumangrassPriceKeeperInternalUsecasesJupiter1(out *jwriter.Writer, in PriceData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.String(string(in.Price))
	}
	out.RawByte('}')
}
