// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  keeper

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( NewPairRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* NewPairRequest ) UnmarshalJSON([]byte) error { return nil }
func ( NewPairRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* NewPairRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_NewPairRequest *NewPairRequest

func ( NewTokenRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* NewTokenRequest ) UnmarshalJSON([]byte) error { return nil }
func ( NewTokenRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* NewTokenRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_NewTokenRequest *NewTokenRequest

func ( PairsResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PairsResponse ) UnmarshalJSON([]byte) error { return nil }
func ( PairsResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PairsResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PairsResponse *PairsResponse

func ( TokensResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* TokensResponse ) UnmarshalJSON([]byte) error { return nil }
func ( TokensResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* TokensResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_TokensResponse *TokensResponse
