// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/tokens": {
            "get": {
                "description": "Get paginated list of tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tokens"
                ],
                "summary": "Get tokens list",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Limit for pagination",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "default": "asc",
                        "description": "Order by field",
                        "name": "orderBy",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_usecases_keeper.TokensResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_humangrass_price-keeper_pgk_xhttp.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_humangrass_price-keeper_pgk_xhttp.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Add a new token to the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tokens"
                ],
                "summary": "Create new token",
                "parameters": [
                    {
                        "description": "Token data",
                        "name": "token",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_usecases_keeper.NewTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_humangrass_price-keeper_pgk_xhttp.ErrorResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_humangrass_price-keeper_pgk_xhttp.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_humangrass_price-keeper_pgk_xhttp.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_humangrass_price-keeper_pgk_xhttp.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "internal_usecases_keeper.NewTokenRequest": {
            "type": "object",
            "required": [
                "name",
                "network",
                "network_id",
                "symbol"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 100
                },
                "network": {
                    "type": "string",
                    "maxLength": 100
                },
                "network_id": {
                    "type": "string",
                    "maxLength": 100
                },
                "symbol": {
                    "type": "string",
                    "maxLength": 10
                }
            }
        },
        "internal_usecases_keeper.Token": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "network": {
                    "type": "string"
                },
                "network_id": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "internal_usecases_keeper.TokensResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_usecases_keeper.Token"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8888",
	BasePath:         "/api/",
	Schemes:          []string{},
	Title:            "Price Keeper API",
	Description:      "API for cryptocurrency tokens",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
